name: qr_code_gen
description: A Material You themed QRCode generator - Create, Save, Scan QR codes
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+3004.2023

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  path_provider: ^2.0.14
  gallery_saver: ^2.3.2
  share_plus: ^6.3.2
  package_info_plus: ^3.1.2
  url_launcher: ^6.1.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.0.4
  shared_preferences: ^2.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#F4D9CE"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway     
      fonts:
        - asset: assets/font/Raleway-Regular.ttf
        - asset: assets/font/Raleway-Black.ttf
          weight: 900
        - asset: assets/font/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Raleway-Bold.ttf
          weight: 700
        - asset: assets/font/Raleway-Italic.ttf
          style: italic
        - asset: assets/font/Raleway-Medium.ttf
          weight: 500
        - asset: assets/font/Raleway-Light.ttf
          weight: 300
        
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
