name: qr_code_gen
description: A Material You themed QRCode generator - Create, Save, Scan QR codes
publish_to: "none"

version: 1.3.0+2024.062216

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  device_info_plus: ^10.0.1
  dynamic_color: ^1.6.0
  flex_color_scheme: ^7.0.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  image_picker: ^1.1.0
  intl: ^0.19.0
  mobile_scanner: ^5.0.0
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.0.14
  permission_handler: ^11.3.1
  qr_flutter: ^4.0.0
  saver_gallery: ^3.0.5
  share_plus: ^9.0.0
  shared_preferences: ^2.1.0
  sqflite: ^2.3.0
  url_launcher: ^6.1.10
  wifi_iot: ^0.3.19

dev_dependencies:
  dependency_validator: ^4.0.0
  flutter_native_splash: ^2.2.0
  icons_launcher: ^2.1.0
  import_sorter: ^4.6.0
  lint: ^2.0.0

icons_launcher:
  image_path: "assets/icon/app_icon.png"
  platforms:
    android:
      enable: true
      image_path: "assets/icon/app_icon.png"
      adaptive_foreground_image: "assets/icon/app_icon_foreground.png"
      adaptive_background_color: "#f4d9ce"
      adaptive_monochrome_image: "assets/icon/app_icon_mono.png"
    ios:
      enable: true
      image_path: "assets/icon/app_icon.png"
    web:
      enable: false

flutter_native_splash:
  color: "#FDFCFF"
  color_dark: "#1A1C1E"
  image: assets/icon/app_icon.png
  android_12:
    color: "#FDFCFF"
    color_dark: "#1A1C1E"
    image: assets/icon/app_icon_foreground.png
    icon_background_color: "#f4d9ce"
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Regular.ttf
        - asset: assets/font/Raleway-Black.ttf
          weight: 900
        - asset: assets/font/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Raleway-Bold.ttf
          weight: 700
        - asset: assets/font/Raleway-Italic.ttf
          style: italic
        - asset: assets/font/Raleway-Medium.ttf
          weight: 500
        - asset: assets/font/Raleway-Light.ttf
          weight: 300

